config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
      resources :sections
      resources :guests do
        resources :rsvp
      end

  end

  resources :rsvp_options

  put 'sections/sort' => 'sections#sort'

  get 'sessions/new' => 'sessions#new'
  get 'sessions/create' => 'sessions#create'
  get 'sessions/destroy' => 'sessions#destroy'
  get 'users/index' => 'users#index'

  get 'users/new' => 'users#new'

  get 'users/create' => 'users#create'

  get 'users/show' => 'users#show'

  get 'users/profile' => 'users#profile'
  get '/invitation/:hash' => 'guests#validate', as: :invitation
  root to: 'users#profile'

  post '/send_invitations/:id' => 'guests#send_invitations', as: :send_invitations

  post 'guests/add' => 'guests#add'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
 end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :sections
  has_many :guests
  has_many :rsvp_options
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :event
  #accepts_nested_attributes_for :rsvp_options

end

app/models/rsvp_option.rb
class RsvpOption < ActiveRecord::Base
  belongs_to :event
  has_many :rsvp_option_values
  accepts_nested_attributes_for :rsvp_option_values, allow_destroy: true
end

app/models/rsvp_option_value.rb
class RsvpOptionValue < ActiveRecord::Base
  belongs_to :rsvp_option
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :event
  default_scope { order("sort_order ASC, id ASC") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  unless Rails.env.development?
    protect_from_forgery with: :exception
  end

  before_action :set_locale

  def set_locale
    if cookies[:planner_locale] && I18n.available_locales.include?(cookies[:planner_locale].to_sym)
      l = cookies[:planner_locale].to_sym
    else
      l = I18n.default_locale
      cookies.permanent[:planner_locale] = l
    end
    I18n.locale = l
  end

  helper_method :current_guest
    def current_guest
      if @current_guest.nil?
        @current_guest = Guest.find_by(access_hash: session[:guest_hash])
      end
    @current_guest
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html, :js

  def new
    @user = current_user
    @event = Event.new(user_id: @user.id)
    @event.event_date = DateTime.now
  end

  def create
    @event = Event.create(event_params)
    @user = current_user
    #binding.pry
    redirect_to '/users/profile'
  end

  def edit
    #binding.pry
    @event = Event.find(params[:id])
    @guest = Guest.new
    @section = Section.new
    @rsvp_option = RsvpOption.new
    @rsvp_option.rsvp_option_values.new
    render 'main'
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(event_params)
    redirect_to edit_event_path
  end

  def show
    @event = Event.find(params[:id])
    @guest = Guest.new

    @rsvp_option = RsvpOption.new
    @event.rsvp_options.build
  end

  private
    def event_params
         params.require(:event).permit(:name, :user_id, :event_date, :location, :latitude, :longitude)
    end
end

app/controllers/guests_controller.rb
require 'faker'

class GuestsController < ApplicationController
  def index
  end

  def add
    @event = Event.find(params[:event])
    guests = params[:guests]
    guests.each do |guest|

      g = Guest.find_or_initialize_by(email: guest['email'], event_id: @event.id)
      g.name = guest['name']

      if g.new_record?
        g.access_hash = Faker::Lorem.characters(30)
      end
      g.save
    end
    #binding.pry
    render partial: 'events/guests_list'
  end

  def validate
    binding.pry
    @guest = Guest.find_by(access_hash: params[:hash])
    if @guest
      @event = @guest.event
      redirect_to event_path @event

    else
    end

  end

  def send_invitations
    @event = Event.find(params[:id])
    @event.guests.where("not notified").each do |guest|
      GuestMailer.invite(guest).deliver_now
      guest.notified = true
      guest.save
    end
  end

  def edit
  end

  def new
    @event = Event.find(params[:id])
    @Section = Section.new
  end

  def create
  end

  def show
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    @section = Section.new
  end

  def create
    #binding.pry
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section.post, notice: 'Section was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @section}
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @section.update_attributes(section_params)
    respond_to do |format|
      format.js
    end
  end

  def sort
    #binding.pry
    params[:sort_order].each do |key,value|
      Section.find(value[:id]).update_attribute(:sort_order,value[:position])
    end
    render :nothing => true
  end

  private
    def section_params
         params.require(:section).permit(:title, :content, :event_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #binding.pry
    user = User.find_by(email:
                          params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       redirect_to users_profile_path
    else
       redirect_to '/login'
    end
end

  def destroy
    session.clear
    redirect_to '/login'
  end

  def guest_create
    #binding.pry
    guest = Guest.find_by(hassh:
                          params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       redirect_to users_profile_path
    else
       redirect_to '/login'
    end
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:planner_locale] = l
    redirect_to request.referer || root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def new
  end

  def profile
    @user = current_user
    #@user.events.build
    #render 'users/profile'
  end

  def create
    # BCrypt::Password.create("my password").gsub(/\//, '')
    #Faker::Lorem.characters(10) #=> "ang9cbhoa8"
  end

  def show
  end

  def events
    @user = User.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # def current_guest
  #   @current_guest ||= Guest.find_by(access_hash: session[:guest_hash])
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_edit.html.erb
<div class="row">
  <div class="col-md-6">
      <%= render 'events/form' %>
  </div>
<div class="col-md-6">
    <div id="map"></div>
  </div>
</div>


<script src="https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=places&callback=initMap" async defer></script>

app/views/events/_form.html.erb
<%= form_for @event, html: {class: 'event-form'} do |f| %>
  <div class="col-md-12">
    <%= render 'events/error_messages' %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', :required => true, oninvalid: "try{setCustomValidity('#{t('forms.required')}')}catch(e){}" %>
      </div>
      <div class="form-group">
        <%= f.label :event_date %>
        <div class='input-group date' id='event-datetimepicker'>

          <%= f.text_field :event_date, class: 'form-control',
              :required => true,
              :value => @event.event_date.strftime("%d/%m/%Y HH:MM"),
              oninvalid: "try{setCustomValidity('#{t('forms.required')}')}catch(e){}"  %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
      <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location , class: 'form-control controls' %>
          <%= f.hidden_field :latitude %>
          <%= f.hidden_field :longitude %>
          <%= f.hidden_field :user_id, value: @event.user_id  %>
      </div>
    </div>
    <div class="col-md-2">
      <%= f.submit t('forms.add'), class:'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/events/_form_guest.html.erb
<%= form_for([@event, @guest]) do |f| %>
  <div class="row">
    <%= f.text_field :name %>
    <%= f.text_field :email %>
    <%= f.submit t('.add_guest'), :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/_guests.html.erb
<h3>Guest List</h3>
<div class="row">
  <div class="col-md-6">
    <%= render  "new_guests" %>
  </div>
  <div class="col-md-6">
    <%= simple_format t 'guests.hint' %>
  </div>
  <div class="col-md-6">
    <%= link_to t('guests.send_invitations'),  send_invitations_path,
        method: 'post', remote: true, class: 'btn btn-primary' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div id="guest-list">
      <% if @event.guests.count > 0 %>

        <%= render  "guests_list" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_guests_list.html.erb
<table class="table">
  <tr>
    <th>
      <%= t 'guests.name' %>
    </th>
    <th>
      <%= t 'guests.email' %>
    </th>
    <th>
      <%= t 'guests.attending' %>
    </th>
    <th>
      <%= t 'guests.notified' %>
    </th>
  </tr>
  <% @event.guests.each do |guest| %>
    <tr>
      <td>
        <%=  guest.name %>
      </td>
      <td>
        <%= guest.email %>
      </td>
      <td>
        <% if guest.attending %>
           <span class="glyphicon glyphicon-ok attending" aria-hidden="true"></span>
        <% end %>
      </td>
      <td>
        <% if guest.notified %>
           <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <% end %>
      </td>
      <td>
        <button class="btn btn-default" ><%= t('forms.edit') %></button>
      </td>
    </tr>
  <% end %>
</table>

app/views/events/_index.html.erb
<%= link_to t('.add_event'), new_event_path, class: 'btn btn-default' %>
  <ul class="user-events list-group">
    <% @user.events.each  do |event| %>
      <li  class="list-group-item">
        <%= link_to event.name, edit_event_path(id: event.id)  %>
        <span class="event-date">
          <%= l(event.event_date, :format => :long) %>
        </span>
      </li>
    <% end %>
  </ul>

app/views/events/_new_guests.html.erb
<%= form_tag '#', id: @event.id, class: "guests-form" do %>
  <%= hidden_field_tag 'event', @event.id %>
  <div>
    <%= text_area_tag 'new_guests', '', size: "50x10"  %>
  </div>
  <div>
    <%= submit_tag t('forms.save'), id:"send-guests", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/_options.html.erb
<h3><%=  t 'events.main.guest_options' %></h3>
<div class="row">
  <div class="col-md-12">
    <div class="bg-success"><%= simple_format (t 'rsvp_options.hint') %></div>
  </div>
  <div class="col-md-12">
    <%= render 'rsvp_options/form' %>
  </div>
</div>

<div class="row">
  <div class="list-unstyled col-md-12 sortable" id="options">
    <% @event.rsvp_options.each do |option| %>
        <%= render partial: 'rsvp_options/form', locals: {rsvp_option: option} %>
    <% end %>
  </div>
</div>

app/views/events/_sections.html.erb
<%=  t 'events.main.sections' %>

<% if @event.sections.count < 5 %>
  <%= render 'sections/form' %>
<% end %>
<div id="new-section"></div>
<div class="row">
<div class="col-md-12">
  <p class="bg-success"><%= t 'sections.notes' %></p>
</div>
<div class="list-unstyled col-md-12 sortable" id="sections">
  <% @event.sections.each do |section| %>
      <%= render partial: 'sections/section', locals: {section: section} %>
  <% end %>
</div>
</div>

app/views/events/main.html.erb
<h2><%= @event.name %></h2>
<%= link_to event_path @event do %>
      <button class="btn btn-default switch-views"><%= t 'events.view_as_guest' %></button>
<% end %>

<ul class="nav nav-tabs event-options" id="event">
  <li><a data-toggle="tab" href="#details"><%= t '.event_details' %></a></li>
  <li><a data-toggle="tab" href="#sections"><%= t '.sections' %></a></li>
  <li class="active"><a data-toggle="tab" href="#guests"><%= t '.guests' %></a></li>
  <li><a data-toggle="tab" href="#options"><%= t '.options' %></a></li>
</ul>

<div class="tab-content">
  <div id="details" class="tab-pane fade">
     <%= render  "edit" %>
  </div>
  <div id="sections" class="tab-pane fade">
     <%= render  "sections" %>
  </div>
  <div id="guests" class="tab-pane fade in active">
    <%= render  "guests" %>
  </div>
  <div id="options" class="tab-pane fade">
    <%= render  "options" %>
  </div>
</div>



  <script>
    $('#event a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    });

    // store the currently selected tab in the hash value
    $("ul.nav-tabs > li > a").on("shown.bs.tab", function (e) {
        var id = $(e.target).attr("href").substr(1);
        window.location.hash = id;
    });

    // on load of the page: switch to the currently selected tab
    var hash = window.location.hash;
    $('#event a[href="' + hash + '"]').tab('show');

</script>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-6">
    <%= render 'events/form' %>
  </div>
  <div class="col-md-6">
      <div id="map"></div>
  </div>
</div>


<script src="https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=places&callback=initMap" async defer></script>

app/views/events/new.js.erb
$('#event-form').html("<%= j (render partial: 'events/form') %>");
$('#event-form').slideDown(350);

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<ul class="nav nav-tabs event-options">
  <% @event.sections.each_with_index  do |section, i| %>
    <li><a data-toggle="tab" href="#<%= i %>"><%= section.title %></a>
    </li>
  <% end %>
  <li>
    <a data-toggle="tab" href="#where-when" class="active"><%= t 'where_when' %></a>
  </li>
  <li>
    <a data-toggle="tab" href="#rsvp">RSVP</a>
  </li>
</ul>

<div class="tab-content">
  <% @event.sections.each_with_index  do |section, i| %>

    <div id="<%= i %>" class="tab-pane">
      <%= section.content %>
    </div>
  <% end %>
  <div id="where-when" class="tab-pane fade in active">
    <div class="row">
      <div class="col-md-6">
        <img class="img-responsive" src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @event.location.gsub(/\s+/, '+') %>&zoom=17&size=600x300&maptype=roadmap
&markers=color:blue%7Clabel:S%7C<%= @event.latitude %>,<%= @event.longitude %>" />
      </div>
      <div class="col-md-6">
        <h2><%= @event.name %></h2>
        <%= t('events.take_place') %>
        <%= l(@event.event_date, :format => :long) %><br/>
        <%= t('events.at') %>: <%= @event.location %>
      </div>

    </div>
  </div>
  <div id="rsvp" class="tab-pane fade">
    <%= render  "/guests/options_form" %>
  </div>
</div>

app/views/guests/_options_form.html.erb
<%= form_for [@event, @guest] do |f| %>

  <%= f.label :attending %>
    <%= f.check_box :attending %>


<% end %>

app/views/guests/send_invitations.js.erb
console.log('hecho')
// *TODO*, dynamically update the ticks

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wedding Planner</title>
  <link href='//fonts.googleapis.com/css?family=Sofia'
        rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body  class="<%= controller_name %> <%= action_name %>">

  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Wedding Planner', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= t('menu.languages.lang') %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to t('menu.languages.en'), change_locale_path(:en) %>
          </li>
          <li>
            <%= link_to t('menu.languages.es'), change_locale_path(:es) %>
          </li>
        </ul>
      </li>
      <li>
        <% if user_signed_in? %>
          <p class="navbar-text navbar-right">
            <%= link_to t('Sign out'), destroy_user_session_path,
                method: 'DELETE' %>
          </p>
        <% else %>
          <p class="navbar-text navbar-right">
            <%= link_to t('Sign_up'), new_user_registration_path %> |
            <%= link_to t('Sign_in'), new_user_session_path %>
          </p>
        <% end %>
      </li>
    </ul>
    </div>
  </div>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <div class="page-header">
      <h1><%= yield :page_header %></h1>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/rsvp_options/_form.html.erb
<%= form_for @rsvp_option do |f| %>

  <ul class="list-unstyled">
    <li>
      <div class="form-group">
        <%= f.label :option_name, t('rsvp_options.name') %>
        <%= f.text_field :option_name %>
      </div>
      <ul class="unstyled-list">
        <%= f.fields_for :rsvp_option_values do |values_form| %>
          <li>
            <div class="form-group">
              <%= values_form.label :value, t('rsvp_options.values') %>
              <%= values_form.text_field :value %>
            </div>
            <div class="form-group">
            <%= values_form.check_box :_destroy %>
            <%= values_form.label :_destroy, "Remove Option" %>
            </div>
          </li>
        <% end %>
        <%= f.submit t('forms.add'), class:'btn btn-primary' %>
      </ul>
    </li>
  </ul>
<% end %>

app/views/sections/_error_messages.html.erb
<div id="error_message">
  <% if @section.errors.any? %>
    <ul>
      <% @section.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/sections/_form.html.erb
<div class="row">

  <%= form_for [@event, @section], remote: true do |f| %>
  <div class="col-md-12">
    <%= render 'sections/error_messages' %>
  </div>
  <div class="col-md-3">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content , size: "30x10", class: 'form-control', placeholder: "Provide content here." %>
        <%= f.hidden_field :event_id, value: @event.id %>
    </div>
    <div class="col-md-2">
      <%= f.submit t('forms.add'), class:'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/sections/_section.html.erb
<div class="panel panel-default"  data-id="<%= section.id %>">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= section.title %>
    </h3>
  </div>
  <div class="panel-body">
    <%= truncate section.content , length: 300 %>
  </div>
</div>

app/views/sections/create.js.erb
console.log("create.js.erb file");
$('#sections').append("<%= j (render partial: 'sections/section', locals: {section: @section} ) %>");

if ($('.panel').length >= 5){
  $('#new_section').hide();
} else {
  $("#new_section")[0].reset();
}

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/profile.html.erb
<h2>Welcome to your wedding planner <%= current_user.name %>!</h2>
<p>
<strong>
  Email:
</strong><%= current_user.email %>


<%= render partial: 'events/index'%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>